# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_median <- function(x, windowSize = 5L) {
    .Call(`_MazamaRollUtils_roll_median`, x, windowSize)
}

roll_mean <- function(x, windowSize = 5L) {
    .Call(`_MazamaRollUtils_roll_mean`, x, windowSize)
}

roll_var <- function(x, windowSize = 5L) {
    .Call(`_MazamaRollUtils_roll_var`, x, windowSize)
}

roll_sd <- function(x, windowSize = 5L) {
    .Call(`_MazamaRollUtils_roll_sd`, x, windowSize)
}

roll_hampel <- function(x, windowSize = 5L, threshold = 1) {
    .Call(`_MazamaRollUtils_roll_hampel`, x, windowSize, threshold)
}

